### ISSUE TITLE
Typo in documentation and/or source code

### ISSUE THREAD

**Issue by bmeh** [lrstanley/girc#17]
At https://godoc.org/github.com/lrstanley/girc#Event, `EmptyTrailign` should be `EmptyTrailing`.
I also recommend replacing all occurrences of `rfc` to `RFC`, as it is an abbreviation.
There is also an inconsistent use of contractions, somewhere you are using the full form, somewhere you are using the contracted form.

**Comment by lrstanley** [comment]
Fixed spelling mistake. As for `rfc`->`RFC` -- have plans to move all of the RFC stuff into a automatically updating/generated `ircdefs` package, just haven't had the chance. Should have some time within the next few weeks though, as I'm just about finished moving places IRL.

**Comment by bmeh** [comment]
Oh, hope things are well! :+1:

**Comment by lrstanley** [comment]
After looking at my uses of "rfc", I won't be making the change. Going off how the IETF references their "rfc#####" more frequently from my brief scans of their sites, it's meh. Still will be moving to an ircdefs separate package which will be auto-generated -- keep an eye out for this.
