### ISSUE TITLE
WebIRC

### ISSUE THREAD

**Issue by qaisjp** [lrstanley/girc#33]
I currently use https://github.com/thoj/go-ircevent/ where I implemented WebIRC support in https://github.com/thoj/go-ircevent/pull/96.

I am interested in girc and would like to add WebIRC support.

Is this fine?

**Comment by lrstanley** [comment]
Are the fields always consistent? e.g. user, hostname, ip should always be provided? If so, may want to make a custom `WebIRC` type that the user specifies, with those fields.

**Comment by qaisjp** [comment]
All are required

**Comment by lrstanley** [comment]
Let me know how https://github.com/lrstanley/girc/commit/c1e59a02f4889054b185088cb6ed79db9641251c works for you. Wanted to be a little be more descriptive.

**Comment by qaisjp** [comment]
Looks good, cheers!
