### ISSUE TITLE
Bad who command

### ISSUE THREAD

**Issue by AJolly** [lrstanley/girc#37]
Running this on a test server: 
```
:irc.foonet.com 255 r :I have 2 clients and 0 servers
:irc.foonet.com 265 r 2 2 :Current local users 2, max 2
:irc.foonet.com 266 r 2 2 :Current global users 2, max 2
:irc.foonet.com 375 r :- irc.foonet.com Message of the Day - 
:irc.foonet.com 372 r :- 17/1/2019 0:18
:irc.foonet.com 372 r :- message
:irc.foonet.com 376 r :End of /MOTD command.
:r MODE r :+iwx
JOIN #inout
:r!r@381B2339.5C917854.9C80D685.IP JOIN #inout * :r
WHO #inout %tacuhnr,1
MODE #inout
:irc.foonet.com 353 r = #inout :r!r@381B2339.5C917854.9C80D685.IP @ad!jolly@381B2339.5C917854.9C80D685.IP 
:irc.foonet.com 366 r #inout :End of /NAMES list.
:irc.foonet.com 352 r #inout r 381B2339.5C917854.9C80D685.IP irc.foonet.com r H :0 r

```
It tries to do a WHO asking for a variable name "WHO #inout %tacuhnr,1"

Look around line 170 in builtin.go but unsure how to fix it.  

`

**Comment by lrstanley** [comment]
I'm confused, how is the `WHO` command incorrect? it's doing a WHO against the channel, and inquiring about the arguments `%tacuhnr`, and `,1` is a client-choice option that allows the client to map who made the request back to the correct client (e.g. ZNC).

**Comment by AJolly** [comment]
Entirely my mistake then.  Was trying to debug an issue with matterbridge (which uses this as a library).
Googled around and did not find anything about options for the who command, thought it was a bug. 

Thanks for your help!
