### ISSUE TITLE
Implement splitting of long messages?

### ISSUE THREAD

**Issue by nmeum** [lrstanley/girc#41]
From [RFC 2812](https://tools.ietf.org/html/rfc2812#section-2.3):

> IRC messages are always lines of characters terminated with a CR-LF (Carriage Return - Line Feed) pair, and these messages SHALL NOT exceed 512 characters in length, counting all characters including the trailing CR-LF.

As I understand it, this is a restriction which applies to messages sent by the server. The client needs to make sure that sent client messages do not result in server messages which exceed this limit. This requires some heuristics to determine the length of the resulting server message for a given client message. Which, in turn, requires calculating the maximum nick and host length et cetera. I personally think that this is a major defect of the IRC protocol itself as it requires implementing "dodgy hacks for every single command" which may exceed this message length. As such, this has also been discussed by the IRv3 working group [\[1\]](https://github.com/ircv3/ircv3-specifications/pull/281).

Short-term it would nice to implement splitting of messages which exceed this limit. For instance, if a PRIVMSG exceeds it, it has to be split into two PRIVMSG commands. I started working on such an [implementation in my own IRC client](https://github.com/nmeum/hii/commit/7d1cfdf9d53b4259bb46b0bb39989450f1ad319c), which uses girc, however I personally think that message splitting would be best implemented in girc itself. What are your thoughts on this?

Existing "message splitting" implementations:

* The irssi implementation: https://github.com/irssi/irssi/blob/6933134352fdd4f53bc2de14b782a743f1290526/src/irc/core/irc-servers.c#L200
* The weechat implementation: https://github.com/weechat/weechat/blob/0d9b7ec95499de6dd0ab981411416be6707b9f25/src/plugins/irc/irc-message.c#L997

Maybe it would make sense to start with an implementation of message splitting for PRIVMSGs and maybe extend it to other commands afterwards?

**Comment by lrstanley** [comment]
I think it should be built into the library, especially with IRCv3 where this limit is larger, and servers can even raise the limit. If I have time, I can take a look.

**Comment by nmeum** [comment]
Great, I would also be willing to work on this as I need it for my own client anyhow. Let me know if I can be of assistance.
