### ISSUE TITLE
Cmd.Part and Cmd.PartMessage attempt to JOIN instead of PART

### ISSUE THREAD

**Issue by puffrfish** [lrstanley/girc#7]
When using the client commands Part and PartMessage a JOIN will be sent instead of a PART.

client.Cmd.Part("#mychannel", "poof")
client.Cmd.PartMessage("#mychannel", "poof")

```2017/11/09 19:37:52 puffrfish: !part
debug:19:37:52 conn.go:451: > JOIN #mychannel
debug:19:37:52 conn.go:451: > JOIN #mychannel :poof```

**Comment by lrstanley** [comment]
merged PR. closing.
